version: '3.7'
services:
    postgres:
        image: postgres:latest
        container_name: db
        restart: always
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
